# Generated by Django 5.0.2 on 2024-10-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="approved_ai_usage",
            field=models.BooleanField(default=False),
        ),
    ]
