# Generated by Django 5.0.2 on 2024-10-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_approved_ai_usage"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_mod",
            field=models.BooleanField(default=False),
        ),
    ]
