# Generated by Django 5.0.2 on 2024-10-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_is_admin_customuser_is_mod"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="flagged",
            field=models.BooleanField(default=False),
        ),
    ]
