# Generated by Django 5.0.2 on 2024-11-07 16:50

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="JPEG",
                keep_meta=False,
                quality=100,
                scale=1,
                size=[64, 64],
                upload_to="profile_pictures/",
            ),
        ),
    ]
