# Generated by Django 5.0.2 on 2024-11-18 03:51

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_customuser_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=["middle", "center"],
                force_format="JPEG",
                keep_meta=False,
                quality=100,
                scale=1,
                size=[64, 64],
                upload_to="profile_pictures/",
            ),
        ),
    ]
