# Generated by Django 5.0.2 on 2024-10-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="is_listicle",
            field=models.BooleanField(default=False),
        ),
    ]
