# Generated by Django 5.0.2 on 2024-10-12 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_blogpost_is_listicle"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reply",
                to="blogs.comment",
            ),
        ),
        migrations.DeleteModel(
            name="ReplyTo",
        ),
    ]
