# Generated by Django 5.0.2 on 2024-10-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0004_alter_comment_post_alter_comment_reply_to_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="flagged",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="comment",
            name="flagged",
            field=models.BooleanField(default=False),
        ),
    ]
