# Generated by Django 5.0.2 on 2024-10-26 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0005_blogpost_flagged_comment_flagged"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="thumbnail",
            field=models.ImageField(blank=True, upload_to="blog_thumbnails/"),
        ),
    ]
