# Generated by Django 5.0.2 on 2024-11-07 16:50

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0007_alter_blogpost_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="thumbnail",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="JPEG",
                keep_meta=False,
                quality=100,
                scale=1,
                size=[520, 292],
                upload_to="blog_thumbnails/",
            ),
        ),
    ]
