# Generated by Django 5.0.2 on 2024-12-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0009_alter_blogpost_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="slug_field",
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
