# Generated by Django 5.0.2 on 2025-01-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0012_blogpost_post_type_commentreaction_reaction_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="post_type",
            field=models.CharField(
                choices=[("blogPost", "Blog Post"), ("list", "Listicle")],
                default="blogPost",
            ),
        ),
    ]
