# Generated by Django 5.0.2 on 2025-01-21 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0013_alter_blogpost_post_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commentreaction",
            old_name="reaction_type",
            new_name="post_type",
        ),
        migrations.RenameField(
            model_name="postcomment",
            old_name="comment_type",
            new_name="post_type",
        ),
        migrations.RenameField(
            model_name="postreaction",
            old_name="reaction_type",
            new_name="post_type",
        ),
    ]
