# Generated by Django 5.0.2 on 2025-01-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0014_rename_reaction_type_commentreaction_post_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentreaction",
            name="post_type",
            field=models.CharField(
                choices=[("blogPost", "Blog Post"), ("list", "Listicle")],
                default="blogPost",
            ),
        ),
        migrations.AlterField(
            model_name="postcomment",
            name="post_type",
            field=models.CharField(
                choices=[("blogPost", "Blog Post"), ("list", "Listicle")],
                default="blogPost",
            ),
        ),
        migrations.AlterField(
            model_name="postreaction",
            name="post_type",
            field=models.CharField(
                choices=[("blogPost", "Blog Post"), ("list", "Listicle")],
                default="blogPost",
            ),
        ),
    ]
