# Generated by Django 5.0.2 on 2025-01-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0016_crosspost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="post_type",
            field=models.CharField(
                choices=[
                    ("blogPost", "Blog Post"),
                    ("list", "Listicle"),
                    ("crosspost", "Crosspost"),
                ],
                default="blogPost",
            ),
        ),
        migrations.AlterField(
            model_name="commentreaction",
            name="post_type",
            field=models.CharField(
                choices=[
                    ("blogPost", "Blog Post"),
                    ("list", "Listicle"),
                    ("crosspost", "Crosspost"),
                ],
                default="blogPost",
            ),
        ),
        migrations.AlterField(
            model_name="postcomment",
            name="post_type",
            field=models.CharField(
                choices=[
                    ("blogPost", "Blog Post"),
                    ("list", "Listicle"),
                    ("crosspost", "Crosspost"),
                ],
                default="blogPost",
            ),
        ),
        migrations.AlterField(
            model_name="postreaction",
            name="post_type",
            field=models.CharField(
                choices=[
                    ("blogPost", "Blog Post"),
                    ("list", "Listicle"),
                    ("crosspost", "Crosspost"),
                ],
                default="blogPost",
            ),
        ),
    ]
