# Generated by Django 5.0.2 on 2025-01-24 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0017_alter_blogpost_post_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crosspost",
            name="blog_post",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="blogs.blogpost"
            ),
        ),
    ]
