# Generated by Django 5.0.2 on 2025-01-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0018_alter_crosspost_blog_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="crosspost",
            name="crosspost_type",
            field=models.CharField(
                choices=[
                    ("blogPost", "Blog Post"),
                    ("list", "Listicle"),
                    ("crosspost", "Crosspost"),
                ],
                default="blogPost",
            ),
        ),
    ]
