# Generated by Django 5.0.2 on 2025-02-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0019_crosspost_crosspost_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
    ]
