# Generated by Django 5.0.2 on 2025-02-06 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0020_blogpost_enabled"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Follower",
        ),
    ]
