services:
    frontend:
        container_name: frontend
        environment: 
            - IS_FRONTEND_PROD=${IS_FRONTEND_PROD}
        build:
            context: ./frontend
            dockerfile: ./Dockerfile
        expose:
            - "6901:6901"
        develop:
            watch:
                - action: sync
                  path: ./frontend
                  target: /frontend_src
                  ignore: 
                    - node_modules/

    backend:
        environment:
            - DATABASE_NAME=${DATABASE_NAME}
            - DATABASE_USER=${DATABASE_USER}
            - DATABASE_PASSWORD=${DATABASE_PASSWORD}
            - DATABASE_PORT=${DATABASE_PORT}
            - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
            - DEBUG=${DEBUG}
            - ALLOWED_HOSTS=${ALLOWED_HOSTS}
            - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
            - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
            - CSRF_COOKIE_SAMESITE=${CSRF_COOKIE_SAMESITE}
            - SESSION_COOKIE_SAMESITE=${SESSION_COOKIE_SAMESITE}
            - CSRF_COOKIE_HTTPONLY=${CSRF_COOKIE_HTTPONLY}
            - SESSION_COOKIE_HTTPONLY=${SESSION_COOKIE_HTTPONLY}
            - CSRF_COOKIE_SECURE=${CSRF_COOKIE_SECURE}
            - SESSION_COOKIE_SECURE=${SESSION_COOKIE_SECURE}
            - CORS_EXPOSE_HEADERS=${CORS_EXPOSE_HEADERS}
            - CORS_ALLOW_CREDENTIALS=${CORS_ALLOW_CREDENTIALS}
            - IS_BACKEND_PROD=${IS_BACKEND_PROD}
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
            - AWS_S3_ENDPOINT_URL=${AWS_S3_ENDPOINT_URL}
            - AWS_DEFAULT_ACL=${AWS_DEFAULT_ACL}
            - STATICFILES_STORAGE=${STATICFILES_STORAGE}
            - STATIC_URL=${STATIC_URL}
            - STATIC_ROOT=${STATIC_ROOT}
            - USE_STORAGES=${USE_STORAGES}
            - AWS_QUERYSTRING_AUTH=${AWS_QUERYSTRING_AUTH}
            - DATABASE_HOST=${DATABASE_HOST}
        container_name: backend
        build: 
            context: ./backend
            dockerfile: ./Dockerfile
        expose:
            - "6900:6900"
        develop:
            watch:
                - action: sync
                  path: ./backend
                  target: /backend_src
        restart: unless-stopped

    nginx:
        container_name: nginx
        build: 
            context: ./nginx
            dockerfile: ./Dockerfile
            target: ${NGINX_TARGET}
        ports:
            - "1337:80"
        depends_on:
            - "backend"
