# Generated by Django 5.0.2 on 2025-01-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crossposts", "0003_crosspostcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="crosspost",
            name="url",
            field=models.URLField(default="https://byeai.dev", max_length=500),
        ),
    ]
